# TODO: Not working
version: '3'
services:
  db:
    image: postgres

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  webapp:
    build: .
    command: foreman start
    volumes:
      - .:/webapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
