default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *default
  database: rails_komponent_stimulus_fish_development

test:
  <<: *default
  database: rails_komponent_stimulus_fish_test

production:
  <<: *default
  username: postgres
  database: rails_komponent_stimulus_fish_production
  password: rails_komponent_stimulus_fish
